- name: Maker directory for install
  become_user: ubuntu
  shell: mkdir -p ~/backend

- name: Extract backend to folder
  become_user: ubuntu
  unarchive:
    src: /home/backend.tar.gz
    dest: ~/backend
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Install dependencies and build
  become: true
  shell: |
    cd ~/backend
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build

- name: Run PM2 server
  shell: |
    cd backend
    pm2 start npm --name backend -- start