- name: Deploy backend app
  become_user: ubuntu
  unarchive:
    src: ../../backend/app.tar.gz
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Install dependencies
  shell: |
    cd /home/ubuntu/backend
    ls -la
    printenv
    npm install
    npm run prestart:prod

- name: Start pm2 (run backend app)
  become_user: ubuntu
  shell: |
    cd /home/ubuntu/backend
    pm2 start main.js --name backend --udate-env