- name: Copy backend files
  become: true
  copy:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Install dependencies
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    mv home/circleci/project/backend .
    cd backend
    npm install -g npm@latest
    npm install -g webpack-dev-server
    npm install
    npm run build

- name: Build and run PM2 server
  shell: |
    cd backend
    pm2 start npm --name backend -- start